coverage:
  status:
    project:
      default:
        target: auto
        threshold: "1%"
ignore:
  - tests
flag_management:
  default_rules:
    carryforward: false
  unit_tests:
    name: Unit Tests
  integration_tests:
    name: Integration Tests
