[workspace]
members = ["xtask"]

[package]
name = "mokapot"
version = "0.8.0"
edition = "2021"
description = "JVM analysis library"
documentation = "https://docs.rs/mokapot"
license = "MIT"
repository = "https://github.com/henryhchchc/mokapot"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitflags = "2.4"
itertools = "0.12"
thiserror = "1.0"
cesu8 = "1.1"
