[package]
name = "mokapot"
version = "0.9.0"
edition = "2021"
description = "JVM analysis library"
documentation = "https://docs.rs/mokapot"
license = "MIT"
repository = "https://github.com/henryhchchc/mokapot"
keywords = ["jvm", "java", "analysis", "bytecode"]


[dependencies]
bitflags = "2.4"
cesu8 = "1.1"
itertools = "0.12"
petgraph = { version = "0.6", optional = true }
thiserror = "1.0"
zip = { version = "0.6", optional = true, default-features = false, features = [
  "deflate",
] }


[features]
default = ["jar", "petgraph"]
jar = ["dep:zip"]
petgraph = ["dep:petgraph"]
