name: Cargo Build & Test

on:
  push:
    branches: ["main"]
    paths:
      - src/**
      - test_data/**
      - Cargo.toml
      - build.rs
      - .github/workflows/**
  pull_request:

permissions:
  pages: write
  id-token: write

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    name: MokaPot - latest
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
          - beta
          - nightly
    steps:
      - uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: corretto
      - uses: actions/checkout@v3
      - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
      - run: cargo build --all-features --verbose
      - run: cargo test --all-features --verbose
      - run: cargo doc --all-features --no-deps --verbose
        if: ${{ matrix.toolchain == 'stable' }}
      - name: Fix permissions
        run: |
          chmod -v -R +rX "target/doc/" | while read line; do
            echo "::warning title=Invalid file permissions automatically fixed::$line"
          done
      - uses: actions/upload-pages-artifact@v2
        if: ${{ matrix.toolchain == 'stable' }}
        with:
          name: github-pages
          path: target/doc
      - uses: actions/deploy-pages@v2
        if: ${{ matrix.toolchain == 'stable' }}
