name: Publish to Crates.io

on:
  push:
    tags:
      - v**

env:
  CARGO_TERM_COLOR: always

jobs:
  publish_to_crate_io:
    name: Publish to crate.io
    runs-on: ubuntu-latest
    steps:
      - run: rustup update && rustup default
        name: Update Rust
      - uses: actions/setup-java@v4
        name: Setup JDK
        with:
          java-version: 21
          distribution: corretto
      - uses: actions/checkout@v4
        name: Checkout source code
      - name: Cargo Check
        run: cargo check --all-features --verbose
      - name: Test
        run: cargo nextest run --all-features --verbose
      - name: Publish to crates.io
        run: cargo publish --all-features --verbose
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
